root: true
extends:
  - standard
  - plugin:prettier/recommended
rules:
  standard/computed-property-even-spacing: off
  semi:
    - error
    - always
  no-extra-semi: error
overrides:
  - files:
      - .mocharc.js
    parserOptions:
      sourceType: script
  - files:
      - test/**/*.spec.js
    env:
      mocha: true
    globals:
      expect: false
      sinon: false
      proxyquire: false
