name: Publish
description: Publish workspaces to npm

inputs:
  token:
    description: 'npm token'
    required: true

runs:
  steps:
    # see https://github.com/google-github-actions/release-please-action#automating-publication-to-npm
    # see https://docs.npmjs.com/generating-provenance-statements
    - name: Checkout Repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Setup Node.js
      uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
      with:
        node-version: 24.20.0
        registry-url: https://registry.npmjs.org
    - name: Install & Build
      uses: bahmutov/npm-install@20216767ca67f0f7b4d095dc5859c5700a6581cb # v1.12.1
    - name: Publish workspaces to npm
      env:
        NODE_AUTH_TOKEN: ${{ inputs.token }}
      run: npm publish --access=public --registry=https://registry.npmjs.org
      shell: bash
  using: composite
