description: Prepares the repo for a typical CI job

name: Prepare
inputs:
  node-version: # id of input
    description: 'Node.js version'
    required: false
    default: '24'

runs:
  steps:
    - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
      with:
        node-version: ${{ inputs.node-version }}
    - name: Install dependencies
      uses: bahmutov/npm-install@20216767ca67f0f7b4d095dc5859c5700a6581cb # v1.12.1
      with:
        install-command: npm ci --foreground-scripts
  using: composite
