name: Node CI

on: [pull_request, push]

permissions:
  contents: read

jobs:
  build:
    name: Node.js v${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [14, 16, 18]
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install latest npm
        run: npm install -g npm
      - name: Install dependencies
        uses: bahmutov/npm-install@cb39a46f27f14697fec763d60fb23ad347e2befa # tag=v1
        with:
          useRollingCache: true
      - name: test
        run: npm test
