name: Publish to npm

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish:
    env:
      token: ${{ secrets.NPM_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - if: ${{ env.token == '' }}
        run: echo "NPM_TOKEN is not set"
      - if: ${{ env.token != '' }}
        name: Checkout Repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - if: ${{ env.token != '' }}
        uses: ./.github/actions/publish
        with:
          token: ${{ secrets.NPM_TOKEN }}
